---
services:
  site:
    build: .
    container_name: izzi-portfolio
    ports:
    - "443:443"
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile
    - ./caddy_data:/data
    - ./certs:/etc/caddy/certs:ro
    environment:
    - DOMAIN=${DOMAIN:-localhost}
    - CERT_FILE=/etc/caddy/certs/localhost.pem
    - CERT_KEY=/etc/caddy/certs/localhost-key.pem
